steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 2000']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/nsd9696/terraform-gcp-test:latest', '.']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/github.com/nsd9696/terraform-gcp-test:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    echo "Docker Container Built"
    ls -la
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes/
  - --image=gcr.io/terraform-test-336308/github.com/nsd9696/terraform-gcp-test:latest
  - --location=asia-northeast2
  - --cluster=cluster-1
  - --timeout=2000s
  timeout: 1200s
timeout: 2000s

# #step 3
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'k8s/']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast2-b'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
# #step 4
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: [
#    'set', 
#    'image', 
#    'deployment', 
#    'myapp', 
#    'myapp=gcr.io/$PROJECT_ID/myapp:$TAG_NAME'
#   ]
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast2-b'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
# # push images to Google Container Registry with tags
# images: [
#    'gcr.io/$PROJECT_ID/<app-name>:$TAG_NAME',
#    'gcr.io/$PROJECT_ID/<app-name>:latest'
#  ]
