apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-denoise-temp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-denoise-temp
  template:
    metadata:
      labels:
        app: image-denoise-temp
    spec:
      containers:
      - name: cv-app-temp
        image: gcr.io/image-denoise-330704/github.com/nsd9696/konkuk_graduate_project:latest
        ports:
        - containerPort: 8501