apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-denoise
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-denoise
  template:
    metadata:
      labels:
        app: image-denoise
    spec:
      containers:
      - name: cv-app
        image: gcr.io/image-denoise-330704/github.com/nsd9696/konkuk_graduate_project:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        ports:
        - containerPort: 8501
  minReadySeconds: 1200
  progressDeadlineSeconds: 2000