apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-denoise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-denoise
  template:
    metadata:
      labels:
        app: image-denoise
    spec:
      containers:
      - name: cv-app
        image: gcr.io/image-denoise-330704/myapp:v1
        ports:
        - containerPort: 8501